Repository 96limshyun/Meet-Your-Books, pull requests merged in 2024-12, with the labels that each got.

#1 feat: 패널 기능 추가
  src/components/Common/Input/Input.tsx
  src/components/Common/Overlay/Overlay.tsx
  src/components/Layout/DefaultLayout.tsx
  src/components/header/DropDownBox/DropDownBox.tsx
  src/components/header/NavigationPanel/NavigationPanel.tsx
  src/constants/index.ts
  src/constants/path.ts
  src/hooks/Common/useOnClickOutside.tsx
  src/pages/Login.tsx
  src/routers/routes.tsx
Labels: enhancement

#3 Feat: 카카오 auth 로그인 기능 구현
  BE/.gitignore
  BE/app.ts
  BE/constants/index.ts
  BE/package-lock.json
  BE/package.json
  BE/routes/auth.ts
  BE/services/fetchAPI.ts
  BE/tsconfig.json
  FE/.gitignore
  FE/README.md
  FE/eslint.config.js
  FE/index.html
  FE/package-lock.json
  FE/package.json
  FE/src/components/Common/Button/Button.tsx
  FE/src/components/Common/Heading/Heading.tsx
  FE/src/components/Common/Image/Image.tsx
  FE/src/components/Common/Input/Input.tsx
  FE/src/components/Common/NoResult/NoResult.tsx
  FE/src/components/Common/Overlay/Overlay.tsx
  FE/src/components/Common/Spacing/Spacing.tsx
  FE/src/components/Common/Text/Text.tsx
  FE/src/components/Common/index.ts
  FE/src/components/Layout/DefaultLayout.tsx
  FE/src/components/header/DropDownBox/DropDownBox.tsx
  FE/src/components/header/HeaderInput/HeaderInput.tsx
  FE/src/components/header/NavigationPanel/NavigationPanel.tsx
  FE/src/components/header/index.tsx
  FE/src/constants/index.ts
  FE/src/constants/path.ts
  FE/src/hooks/Common/useOnClickOutside.tsx
  FE/src/index.css
  FE/src/main.tsx
  FE/src/pages/BookDetail.tsx
  FE/src/pages/FavoriteBook.tsx
  FE/src/pages/Home.tsx
  FE/src/pages/LibraryInfo.tsx
  FE/src/pages/Login.tsx
  FE/src/pages/RegionInfo.tsx
  FE/src/pages/index.ts
  FE/src/routers/routes.tsx
  FE/src/services/APIClient.ts
  FE/src/services/fetch.ts
  FE/src/services/index.ts
  FE/src/styles/globalStyle.ts
  FE/src/styles/theme.ts
  FE/src/types/dropDownType.ts
  FE/src/vite-env.d.ts
  FE/tsconfig.app.json
  FE/tsconfig.json
  FE/tsconfig.node.json
  FE/vite.config.ts
  src/pages/Login.tsx
Labels: design, FE, BE, feature

#5 Feat: 필터 기능 추가
  FE/package-lock.json
  FE/package.json
  FE/src/components/FilterDisplay/DefaultFilterBox/DefaultFilterBox.tsx
  FE/src/components/FilterDisplay/FilterDisplay.tsx
  FE/src/components/FilterDisplay/Header/Header.tsx
  FE/src/components/FilterDisplay/Item/Item.tsx
  FE/src/components/FilterDisplay/KeywordFilter/KeywordFilter.tsx
  FE/src/components/Layout/DefaultLayout.tsx
  FE/src/components/header/DropDownBox/DropDownBox.tsx
  FE/src/components/header/HeaderInput/HeaderInput.tsx
  FE/src/constants/index.ts
  FE/src/hooks/Common/useOpen.tsx
  FE/src/hooks/Queries/useGetQuery.tsx
  FE/src/main.tsx
  FE/src/pages/Home.tsx
  FE/src/stores/bookStore.ts
  FE/src/styles/globalStyle.ts
  FE/src/types/booksType.ts
  FE/src/types/dropDownType.ts
  FE/src/types/keywordType.ts
  FE/vite.config.ts
Labels: design, FE, feature

#9 Feat: ai 도서 추천받기 기능구현
  BE/app.ts
  BE/constants/index.ts
  BE/package-lock.json
  BE/package.json
  BE/routes/auth.ts
  BE/routes/openAI.ts
  BE/types/index.ts
  FE/package-lock.json
  FE/package.json
  FE/src/components/AIChatPopup/AIChatBox/AIChatBox.tsx
  FE/src/components/AIChatPopup/AIChatPopup.tsx
  FE/src/components/Common/Button/Button.tsx
  FE/src/components/Common/Input/Input.tsx
  FE/src/components/Common/Text/Text.tsx
  FE/src/constants/index.ts
  FE/src/pages/Home.tsx
  FE/src/pages/Login.tsx
  FE/src/styles/theme.ts
  FE/src/types/openAIType.ts
Labels: design, FE, BE, feature

#14 Feat: 백엔드 mongoDB 연결 및 댓글 api 기능 구현
  BE/Models/CommentSchema.ts
  BE/app.ts
  BE/package-lock.json
  BE/package.json
  BE/routes/comment.ts
Labels: BE, setting, feature

#16 feat: 도서 상세보기 페이지 구현(상세 정보 불러오기, 리뷰 CRUD)
  BE/Models/CommentSchema.ts
  BE/app.ts
  BE/routes/comment.ts
  FE/src/components/BookDisplay/BookCard/BookCard.tsx
  FE/src/components/BookDisplay/BookDisplay.tsx
  FE/src/components/Detail/BookDetailCard/BookDetailCard.tsx
  FE/src/components/Detail/CommentBox/CommentBox.tsx
  FE/src/components/Detail/CommentCreateTextarea/CommentCreateTextarea.tsx
  FE/src/components/Detail/index.ts
  FE/src/hooks/BookDetail/useBookDetailLogic.tsx
  FE/src/hooks/BookDetail/useCommentHandlers.tsx
  FE/src/hooks/Common/useUserInfo.tsx
  FE/src/hooks/Queries/comments/useCommentQuery.tsx
  FE/src/hooks/Queries/comments/useCreateCommentMutation.tsx
  FE/src/hooks/Queries/comments/useDeleteCommentMutation.tsx
  FE/src/hooks/Queries/comments/usePatchCommentsMutation.tsx
  FE/src/pages/BookDetail.tsx
  FE/src/routers/routes.tsx
  FE/src/services/APIClient.ts
  FE/src/services/index.ts
  FE/src/types/bookDetailType.ts
  FE/src/types/commentsType.ts
  FE/src/utils/index.ts
Labels: design, FE, BE, setting, refactor, feature

#20 [Geroge]: 도서 상세 페이지 차트 기능 구현
  FE/package-lock.json
  FE/package.json
  FE/src/components/Detail/BarRechart/BarRechart.tsx
  FE/src/components/Detail/BookDetailCard/BookDetailCard.tsx
  FE/src/components/Detail/LineRechart/LineRechart.tsx
  FE/src/components/Detail/index.ts
  FE/src/hooks/BookDetail/useBookDetailLogic.tsx
  FE/src/pages/BookDetail.tsx
  FE/src/types/bookDetailType.ts
Labels: design, FE, feature

#18 [Marron] 내가 찜한 책 화면 구현
  BE/Models/FavoriteSchema.ts
  BE/app.ts
  BE/routes/comment.ts
  BE/routes/favorites.ts
  FE/src/components/BookDisplay/BookCard/BookCard.tsx
  FE/src/components/BookDisplay/FavoriteBookDisplay.tsx
  FE/src/components/BookDisplay/ViewSelector/ViewSelector.tsx
  FE/src/components/Common/FavoriteBtn/FavoriteBtn.tsx
  FE/src/hooks/Queries/favorites/useAddFavoriteMutation.tsx
  FE/src/hooks/Queries/favorites/useFavoritesQuery.tsx
  FE/src/hooks/Queries/favorites/useRemoveFavoriteMutation.tsx
  FE/src/pages/FavoriteBook.tsx
  FE/src/services/index.ts
Labels: design, FE, feature

#24 [George] 소장 도서관 기능 구현
  BE/Models/RegionSchema.ts
  BE/app.ts
  BE/routes/comment.ts
  BE/routes/region.ts
  FE/src/components/Common/index.ts
  FE/src/components/Detail/BookDetailCard/BookDetailCard.tsx
  FE/src/components/Detail/LibrariesDisplay/LibrariesDisplay.tsx
  FE/src/components/Detail/LibrariesFindPopup/LibrariesFindPopup.tsx
  FE/src/components/Detail/RegionSelectBox/RegionSelectBox.tsx
  FE/src/components/Layout/DefaultLayout.tsx
  FE/src/constants/index.ts
  FE/src/constants/regions.ts
  FE/src/hooks/Queries/libraryCollection/useSubRegionQuery.tsx
  FE/src/services/index.ts
  FE/src/types/libraryType.ts
  FE/src/types/regionType.ts
Labels: design, FE, BE, feature

#36 feat: openAPI 요청 백엔드로 이전
  BE/app.ts
  BE/routes/libraryOpenAPI.ts
  FE/src/components/Detail/LibrariesDisplay/LibrariesDisplay.tsx
  FE/src/components/FilterDisplay/FilterDisplay.tsx
  FE/src/components/FilterDisplay/KeywordFilter/KeywordFilter.tsx
  FE/src/components/Modal/Modal.tsx
  FE/src/components/Skeletons/FilterSkeleton.tsx
  FE/src/hooks/Book/useBookLogic.tsx
  FE/src/hooks/BookDetail/useBookDetailLogic.tsx
  FE/src/hooks/Queries/Detail/useCheckLoanStatus.tsx
  FE/src/hooks/Queries/useBookInfinityQuery.tsx
  FE/src/hooks/Queries/useDefaultQuery.tsx
  FE/src/hooks/Queries/useDefaultSuspenseQuery.tsx
  FE/src/hooks/Queries/useLibraryOpenAPIQuery.tsx
  FE/src/pages/BookDetail.tsx
Labels: FE, BE, refactor

#40 feat: seo 개선
  FE/index.html
  FE/public/robots.txt
  FE/public/sitemap.xml
Labels: FE

#45 deploy: FE/BE CICD 구축
  .github/workflows/back-deploy.yaml
  .github/workflows/front-deploy.yaml
  FE/src/hooks/Book/useGenerateQuery.tsx
  FE/src/hooks/Queries/useLibraryOpenAPIQuery.tsx
Labels: FE, BE, deploy, feature

#52 feat: 에러바운더리 구현
  BE/routes/libraryOpenAPI.ts
  FE/package-lock.json
  FE/package.json
  FE/src/components/BookDisplay/BookDisplay.tsx
  FE/src/components/ErrorFallBack/ErrorFallBack.tsx
  FE/src/constants/HTTPErrorMessage.ts
  FE/src/hooks/Queries/Detail/useCheckLoanStatus.tsx
  FE/src/hooks/Queries/Detail/useSubRegionQuery.tsx
  FE/src/hooks/Queries/comments/useCommentQuery.tsx
  FE/src/hooks/Queries/comments/useCreateCommentMutation.tsx
  FE/src/hooks/Queries/comments/useDeleteCommentMutation.tsx
  FE/src/hooks/Queries/comments/usePatchCommentsMutation.tsx
  FE/src/hooks/Queries/favorites/useAddFavoriteMutation.tsx
  FE/src/hooks/Queries/favorites/useFavoritesQuery.tsx
  FE/src/hooks/Queries/favorites/useRemoveFavoriteMutation.tsx
  FE/src/hooks/Queries/useBookInfinityQuery.tsx
  FE/src/hooks/Queries/useLibraryOpenAPIQuery.tsx
  FE/src/routers/routes.tsx
Labels: FE, BE, feature

#58 Bug: 댓글 기능 및 상세페에지 팝업 버그 수정
  FE/src/assets/fonts/cinzel-v23-latin-regular.woff2
  FE/src/assets/fonts/nanum-gothic-v26-latin-regular.woff2
  FE/src/components/Detail/LibrariesDisplay/LibrariesDisplay.tsx
  FE/src/components/Detail/LibrariesFindPopup/LibrariesFindPopup.tsx
  FE/src/components/ErrorFallBack/ErrorFallBack.tsx
  FE/src/hooks/BookDetail/useLibrariesDisplayLogic.tsx
  FE/src/hooks/BookDetail/useLibrariesPopupLogic.tsx
  FE/src/hooks/Queries/comments/useCreateCommentMutation.tsx
  FE/src/hooks/Queries/comments/useDeleteCommentMutation.tsx
  FE/src/hooks/Queries/comments/usePatchCommentsMutation.tsx
  FE/src/hooks/Queries/useLibraryOpenAPISuspenseQuery.tsx
  FE/src/index.css
  FE/src/styles/globalStyle.ts
  FE/src/types/commentsType.ts
Labels: bug, FE

#59 deploy: 버그 및 레이아웃 수정 및 배포
  FE/src/components/BookDisplay/FavoriteBookDisplay.tsx
  FE/src/components/Detail/LibrariesDisplay/LibrariesDisplay.tsx
  FE/src/components/Detail/LibrariesFindPopup/LibrariesFindPopup.tsx
  FE/src/components/ErrorFallBack/ErrorFallBack.tsx
  FE/src/components/FavoriteSearchSection/FavoriteSearchInput/FavoriteSearchInput.tsx
  FE/src/components/FavoriteSearchSection/FavoriteSearchSection.tsx
  FE/src/hooks/BookDetail/useLibrariesDisplayLogic.tsx
  FE/src/hooks/BookDetail/useLibrariesPopupLogic.tsx
  FE/src/hooks/Queries/comments/useCreateCommentMutation.tsx
  FE/src/hooks/Queries/comments/useDeleteCommentMutation.tsx
  FE/src/hooks/Queries/comments/usePatchCommentsMutation.tsx
  FE/src/hooks/Queries/useLibraryOpenAPISuspenseQuery.tsx
  FE/src/pages/FavoriteBook.tsx
  FE/src/types/commentsType.ts
Labels: design, FE, refactor, deploy

#62 feat: ai 책 추천 링크 이동 기능 구현
  BE/constants/index.ts
  BE/routes/openAI.ts
  FE/package-lock.json
  FE/package.json
  FE/src/components/AIChatPopup/AIChatBox/AIChatBox.tsx
  FE/src/components/BookDisplay/FavoriteBookDisplay.tsx
  FE/src/hooks/Queries/useLibraryOpenAPISuspenseQuery.tsx
Labels: design, FE, BE, feature

#66 fix: 댓글 작성일이 Nan으로 표시되는 버그 및 검색 버그 수정
  FE/README.md
  FE/public/robots.txt
  FE/src/hooks/Book/useGenerateQuery.tsx
  FE/src/hooks/Queries/comments/useCreateCommentMutation.tsx
  README.md
Labels: bug, FE

#67 feat: Modal 기능 추가
  BE/routes/openAI.ts
  FE/src/components/Common/FavoriteBtn/FavoriteBtn.tsx
  FE/src/components/Common/Modal/Modal.tsx
  FE/src/components/Detail/CommentBox/CommentBox.tsx
  FE/src/components/Detail/LibrariesFindPopup/LibrariesFindPopup.tsx
  FE/src/components/header/NavigationPanel/NavigationPanel.tsx
  README.md
Labels: design, FE, feature

#68 deploy: 모달 기능 추가
  BE/routes/openAI.ts
  FE/src/components/Common/FavoriteBtn/FavoriteBtn.tsx
  FE/src/components/Common/Modal/Modal.tsx
  FE/src/components/Detail/CommentBox/CommentBox.tsx
  FE/src/components/Detail/LibrariesFindPopup/LibrariesFindPopup.tsx
  FE/src/components/header/NavigationPanel/NavigationPanel.tsx
Labels: FE, deploy
